---
driver:
  name: docker
docker:
  containers:
    - name: ansible-role-pithos
      image: centos
      image_version: 7
      ansible_groups:
        - group1
      port_bindings: { 8080: 8080 }
      privileged: True
      volume_mounts:
        - "/sys/fs/cgroup"
      command: "/usr/sbin/init"
      environment: { container: docker }
verifier:
  name: testinfra
