---
dependency:
  name: galaxy
  requirements_file: tests/requirements.yml
  options:
      ignore-certs: True
      ignore-errors: True
driver:
  name: docker
docker:
  containers:
    - name: ansible-role-pithos1
      image: williamyeh/ansible
      image_version: centos7
      ansible_groups:
        - pithos
      port_bindings: { 8080: 8080 }
      privileged: True
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      command: "/usr/sbin/init"
      environment: { container: docker }
    - name: ansible-role-pithos2
      image: williamyeh/ansible
      image_version: centos7
      ansible_groups:
        - pithos
      port_bindings: { 8080: 8081 }
      privileged: True
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      command: "/usr/sbin/init"
      environment: { container: docker }
    - name: ansible-role-pithos3
      image: williamyeh/ansible
      image_version: centos7
      ansible_groups:
        - pithos
      port_bindings: { 8080: 8082 }
      privileged: True
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      command: "/usr/sbin/init"
      environment: { container: docker }
verifier:
  name: testinfra
