---
- hosts: all
  tasks:
    - set_fact: 
        ansible_default_ipv4: 
          address: 127.0.0.1
      when: ansible_default_ipv4 is not defined
    - debug: var=ansible_default_ipv4
  roles:
    - role: pithos
