---
- name: install common pkgs...
  package: name={{item}} state=present
  with_items:
    - tar
    - bsdtar
    - unzip
    - gzip
    - bzip2

- name: RedHat pkgs...
  when: ansible_os_family == 'RedHat'
  package: name={{item}} state=present
  with_items:
    - p7zip

- name: Debian pkgs...
  when: ansible_os_family == 'Debian'
  package: name={{item}} state=present
  with_items:
    - p7zip-full
